# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for
# blackfriday.

language: go

go:
    - 1.5
    - 1.6
    - 1.7

install:
    - mkdir -p $GOPATH/src/github.com/russross/
    - pushd $GOPATH/src/github.com/russross/
    - git clone https://github.com/russross/blackfriday blackfriday.v2
    - cd blackfriday.v2
    - git checkout v2
    - popd
    - go get -d -t -v ./...
    - go build -v ./...

script:
    - go test -v ./...
    - go test -run=^$ -bench=BenchmarkReference -benchmem
